/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "sai_constants.h"

namespace sai {

const saiConstants g_sai_constants;

saiConstants::saiConstants() {
}

} // namespace

