/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef sai_CONSTANTS_H
#define sai_CONSTANTS_H

#include "sai_types.h"

namespace sai {

class saiConstants {
 public:
  saiConstants();

};

extern const saiConstants g_sai_constants;

} // namespace

#endif
